[workspace]
members = ["tusks", "tusks-lib", "tusks-macro", "tusks-tasks", "tusks-test"]
exclude = ["tusks-test-async"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "3.1.0"
authors = ["Benjamin Schnitzler"]
license = "MIT"
repository = "https://github.com/bschnitz/tusks"
description = "Declarative CLI framework built on top of clap"

[workspace.dependencies]
tusks-macro = { version = "3.1.0", path = "tusks-macro" }
tusks-lib = { version = "3.1.0", path = "tusks-lib" }
tusks-tasks = { version = "3.1.0", path = "tusks-tasks" }
tusks = { version = "3.1.0", path = "tusks" }

clap = "4.5.53"
indexmap = "2.12.1"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.108"
unicode-width = "0.2.0"

tokio = { version = "1", default-features = false, features = ["rt", "rt-multi-thread"] }

assert_cmd = "2.1.1"
predicates = "3.1.3"
