/// Returns true for fields that are generated by tusks and should be
/// excluded when iterating user-defined Parameters fields.
pub fn is_generated_field(name: &str) -> bool {
    name == "super_" || name == "_phantom_lifetime_marker"
}
